good

diff --git a/.github/workflows/dashboard_pr.yml b/.github/workflows/dashboard_pr.yml
--- a/.github/workflows/dashboard_pr.yml
+++ b/.github/workflows/dashboard_pr.yml
@@ -28,16 +28,13 @@ jobs:
 
           if ! git diff --quiet; then
             echo "::error::Generated proto files are not up to date."
-            git merge-base origin/$GITHUB_HEAD_REF origin/$GITHUB_BASE_REF
-            FORK_POINT=$(git merge-base origin/$GITHUB_HEAD_REF origin/$GITHUB_BASE_REF)
-            echo "Fork point: $FORK_POINT"
-            if ! git diff --quiet $FORK_POINT..origin/$GITHUB_BASE_REF -- proto; then
-              echo "::notice::Please update your branch first and then run 'npm run gen-proto' at dashboard/ and commit the changes."
-              exit 2
+            FORK_POINT=$(git merge-base $GITHUB_HEAD_REF $GITHUB_BASE_REF)
+            if ! git diff --quiet $FORK_POINT..$GITHUB_BASE_REF -- proto; then
+              echo "::error::Please update your branch first and then run 'npm run gen-proto' at dashboard/ and commit the changes."
             else
-              echo "::notice::Please run 'npm run gen-proto' at dashboard/ and commit the changes."
-              exit 3
+              echo "::error::Please run 'npm run gen-proto' at dashboard/ and commit the changes."
             fi
+            exit 1
           fi
 
           npm run lint
