?

diff --git a/.github/workflows/dashboard_pr.yml b/.github/workflows/dashboard_pr.yml
--- a/.github/workflows/dashboard_pr.yml
+++ b/.github/workflows/dashboard_pr.yml
@@ -26,17 +26,17 @@ jobs:
           npm run gen-proto
 
           if ! git diff --quiet; then
-            echo "::error Generated proto files are not up to date."
+            echo "::error::Generated proto files are not up to date."
             git fetch origin $GITHUB_BASE_REF
             FORK_POINT=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
             echo "Fork point: $FORK_POINT"
             if ! git diff --quiet $FORK_POINT..origin/$GITHUB_BASE_REF -- proto; then
               echo "Please update your branch first and then run 'npm run gen-proto' at dashboard/ and commit the changes."
-              exit 1
+              exit 2
             fi
             
-            echo "::notice Please run 'npm run gen-proto' at dashboard/ and commit the changes."
-            exit 1
+            echo "::notice::Please run 'npm run gen-proto' at dashboard/ and commit the changes."
+            exit 3
           fi
 
           npm run lint
